//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Online_Help_Desk
{
    using System;
    using System.Collections.Generic;
    
    public partial class End_user
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public End_user()
        {
            this.Requests = new HashSet<Request>();
        }
    
        public string EUsername { get; set; }
        public string EPassword { get; set; }
        public string EStatus { get; set; }
        public string EFullname { get; set; }
        public string EGender { get; set; }
        public string EEmail { get; set; }
        public string EPhone { get; set; }
        public string EAddress { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Request> Requests { get; set; }
    }
}
