//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Online_Help_Desk
{
    using System;
    using System.Collections.Generic;
    
    public partial class Request
    {
        public int RID { get; set; }
        public string RTitle { get; set; }
        public string RRemark { get; set; }
        public string RStatus { get; set; }
        public string RFacilityID { get; set; }
        public string RRequestor { get; set; }
        public string RStaffID { get; set; }
        public System.DateTime RDate { get; set; }
        public string RImage { get; set; }
    
        public virtual End_user End_user { get; set; }
        public virtual Facility Facility { get; set; }
        public virtual Staff Staff { get; set; }
    }
}
